Fixed #212
mojohaus/versions-maven-plugin pull request #446
Opened 2021-01-23 12:16 UTC by somejavadev

o Added includes functionality to allow filtering update check by artifact.

2021-01-23 14:28 UTC, somejavadev commented
Seems like most of the latest PR's are failing with the same 33 errors on the `JDKBuilds / OpenJDK 16 (pull_request) Failing after 8m — OpenJDK 1` build.

2021-06-04 04:33 UTC, olamy requested changes
just some easy changes.
can you please rebase as well to get last changes from master?
Thanks

2021-06-04 04:33 UTC, olamy commented on src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
> +     * Limit finding available updates to specific artifacts. Defaults to no limit.
sounds good but can document what could be the content of this. Maybe with samples. Thanks

2021-06-04 04:33 UTC, olamy commented on src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
> +
no need of some return here :)

2022-03-30 11:34 UTC, delanym commented
Does this also place the check after the filter for -DincludesList and -Dexcludes/excludesList ?

2022-08-28 16:46 UTC, closed without merging